---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Ensure unzip is installed
      ansible.builtin.apt:
        name: unzip
        state: present
        update_cache: true
        cache_valid_time: 3600
