---
- name: Upgrade and change the admin password
  hosts: all
  become: true
  vars:
    grafana_version: 13.2.2
    grafana_admin_password: second-password
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
